### ISSUE TITLE
Regions for eyes

### ISSUE THREAD

**Issue by bibidobr** [affromero/OpenCV-Projects#1]
Hei, sorry to disturb you.
I've studied your code and i have a question
How you know to take this values and measures for the regions of the eye?
//Split two different regions for two eyes
///*
Rect eyearea_right = new Rect( RectOfFace.x + RectOfFace.width / 16 ,
(int) (RectOfFace.y + (RectOfFace.height / 4.5)) ,
(RectOfFace.width - 2 * RectOfFace.width / 16) / 2,
(int) (RectOfFace.height / 3.0)
);

        Rect eyearea_left = new Rect( RectOfFace.x + RectOfFace.width / 16 + ( RectOfFace.width - 2 * RectOfFace.width / 16 ) / 2 ,
                 (int) (RectOfFace.y + (RectOfFace.height / 4.5)) , 
                 (RectOfFace.width - 2 * RectOfFace.width / 16) / 2 , 
                 (int) (RectOfFace.height / 3.0)
                 )

**Comment by affromero** [comment]
Hello, those values were purely by try and error i.e., eyes are always expected in the upper region of the face.
